### 1.데이터 불러오기 및 구조 파악

In [222]:
import pandas as pd

df = pd.read_csv("../../data/processed/travel_timing_expenditure_2025.csv")

df.head()

,RESPOND_ID,EXAMIN_BEGIN_DE_x,TOUR_CTPRVN_NM_x,TOUR_SIGNGU_NM_x,TOUR_BEGIN_DE,TOUR_PD_VALUE_x,TOUR_COM_NMPR_NM_x,COM_ONE_TY,COM_TWO_TY,COM_THREE_TY,...,TOUR_CTPRVN_NM_y,TOUR_SIGNGU_NM_y,TOUR_COM_NMPR_NM_y,TOUR_PD_VALUE_y,SEXDSTN_FLAG_CD_y,AGRDE_FLAG_NM_y,MRRG_AT_NM_y,CHLDRN_TY_NM_y,OCCP_NM_y,HSHLD_INCOME_DGREE_NM_y
0,130808,20251117,인천시,모름,20250810,6박 7일 이상,2명,배우자,NaN,NaN,...,인천시,모름,2명,6박 7일 이상,F,60대 이상,기혼,자녀 독립(막내 결혼),기타/무직,300~500만원 미만
1,151677,20251117,경기도,광주시,20251028,1박 2일,2명,배우자,NaN,NaN,...,경기도,광주시,2명,1박 2일,F,60대 이상,기혼,자녀 성인(막내 대학),사무/기술직,700만원 이상
2,156439,20251117,충청북도,단양군/제천시/충주시(구 청원군 포함),20250908,6박 7일 이상,혼자서,혼자서,NaN,NaN,...,충청북도,단양군/제천시/충주시(구 청원군 포함),혼자서,6박 7일 이상,M,30대,미혼,미혼,사무/기술직,500~700만원 미만
3,245007,20251117,전라남도,구체적인 지역 모름,20251008,2박 3일,4명,배우자,부모/형제/자녀 등 가족,NaN,...,전라남도,구체적인 지역 모름,4명,2박 3일,F,40대,기혼,자녀 성장(막내 중고생),기타/무직,모름
4,321410,20251117,경상북도,청도군,20251114,2박 3일,2명,친구,NaN,NaN,...,경상북도,청도군,2명,2박 3일,F,20대,미혼,미혼,사무/기술직,300만원 미만

In [223]:
df.shape

(14342, 38)

In [224]:
df.columns

Index(['RESPOND_ID', 'EXAMIN_BEGIN_DE_x', 'TOUR_CTPRVN_NM_x',
       'TOUR_SIGNGU_NM_x', 'TOUR_BEGIN_DE', 'TOUR_PD_VALUE_x',
       'TOUR_COM_NMPR_NM_x', 'COM_ONE_TY', 'COM_TWO_TY', 'COM_THREE_TY',
       'COM_FOUR_TY', 'COM_FIVE_TY', 'COM_SIX_TY', 'TOUR_PURPS_NM',
       'SEXDSTN_FLAG_CD_x', 'AGRDE_FLAG_NM_x', 'MRRG_AT_NM_x',
       'CHLDRN_TY_NM_x', 'OCCP_NM_x', 'HSHLD_INCOME_DGREE_NM_x',
       'EXAMIN_BEGIN_DE_y', 'TOUR_TOT_CT_VALUE', 'TOUR_LDGMNT_CT_VALUE',
       'TOUR_FOOD_CT_VALUE', 'TOUR_TRNSPORT_CT_VALUE', 'TOUR_SHOPNG_CT_VALUE',
       'TOUR_ACTVTY_CT_VALUE', 'TOUR_ETC_CT_VALUE', 'TOUR_CTPRVN_NM_y',
       'TOUR_SIGNGU_NM_y', 'TOUR_COM_NMPR_NM_y', 'TOUR_PD_VALUE_y',
       'SEXDSTN_FLAG_CD_y', 'AGRDE_FLAG_NM_y', 'MRRG_AT_NM_y',
       'CHLDRN_TY_NM_y', 'OCCP_NM_y', 'HSHLD_INCOME_DGREE_NM_y'],
      dtype='object')

In [225]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14342 entries, 0 to 14341
Data columns (total 38 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   RESPOND_ID               14342 non-null  int64
 1   EXAMIN_BEGIN_DE_x        14342 non-null  int64
 2   TOUR_CTPRVN_NM_x         14342 non-null  object
 3   TOUR_SIGNGU_NM_x         14342 non-null  object
 4   TOUR_BEGIN_DE            14342 non-null  int64
 5   TOUR_PD_VALUE_x          14342 non-null  object
 6   TOUR_COM_NMPR_NM_x       14342 non-null  object
 7   COM_ONE_TY               14207 non-null  object
 8   COM_TWO_TY               2700 non-null   object
 9   COM_THREE_TY             130 non-null    object
 10  COM_FOUR_TY              7 non-null      object
 11  COM_FIVE_TY              2 non-null      object
 12  COM_SIX_TY               0 non-null      float64
 13  TOUR_PURPS_NM            14342 non-null  object
 14  SEXDSTN_FLAG_CD_x        14342 non-null  object
 15  AGRDE_FLAG_NM_x          14342 non-null  object
 16  MRRG_AT_NM_x             14342 non-null  object
 17  CHLDRN_TY_NM_x           14342 non-null  object
 18  OCCP_NM_x                14342 non-null  object
 19  HSHLD_INCOME_DGREE_NM_x  14342 non-null  object
 20  EXAMIN_BEGIN_DE_y        14342 non-null  int64
 21  TOUR_TOT_CT_VALUE        14342 non-null  object
 22  TOUR_LDGMNT_CT_VALUE     14342 non-null  object
 23  TOUR_FOOD_CT_VALUE       14342 non-null  object
 24  TOUR_TRNSPORT_CT_VALUE   14342 non-null  object
 25  TOUR_SHOPNG_CT_VALUE     14342 non-null  object
 26  TOUR_ACTVTY_CT_VALUE     14342 non-null  object
 27  TOUR_ETC_CT_VALUE        14342 non-null  object
 28  TOUR_CTPRVN_NM_y         14342 non-null  object
 29  TOUR_SIGNGU_NM_y         14342 non-null  object
 30  TOUR_COM_NMPR_NM_y       14342 non-null  object
 31  TOUR_PD_VALUE_y          14342 non-null  object
 32  SEXDSTN_FLAG_CD_y        14342 non-null  object
 33  AGRDE_FLAG_NM_y          14342 non-null  object
 34  MRRG_AT_NM_y             14342 non-null  object
 35  CHLDRN_TY_NM_y           14342 non-null  object
 36  OCCP_NM_y                14342 non-null  object
 37  HSHLD_INCOME_DGREE_NM_y  14342 non-null  object
dtypes: float64(1), int64(4), object(33)
memory usage: 4.2+ MB

### 2.결측치 처리

In [226]:
check_cols = [
    'TOUR_BEGIN_DE',
    'TOUR_CTPRVN_NM_x',
    'TOUR_SIGNGU_NM_x',
    'TOUR_PD_VALUE_x',
    'TOUR_PURPS_NM',
    'TOUR_TOT_CT_VALUE'
]

df[check_cols].isnull().sum()

TOUR_BEGIN_DE        0
TOUR_CTPRVN_NM_x     0
TOUR_SIGNGU_NM_x     0
TOUR_PD_VALUE_x      0
TOUR_PURPS_NM        0
TOUR_TOT_CT_VALUE    0
dtype: int64

In [227]:
# 결측치 개수와 비율 확인
missing = pd.DataFrame({
    '결측치수': df.isnull().sum(),
    '결측치비율(%)': df.isnull().mean() * 100
})

missing[missing['결측치수'] > 0].sort_values(
    '결측치비율(%)',
    ascending=False
)

               결측치수    결측치비율(%)
COM_SIX_TY    14342  100.000000
COM_FIVE_TY   14340   99.986055
COM_FOUR_TY   14335   99.951192
COM_THREE_TY  14212   99.093571
COM_TWO_TY    11642   81.174174
COM_ONE_TY      135    0.941291

결측치 처리 결과

- 분석에 사용하는 여행일자, 지역, 여행기간, 여행목적, 여행 총비용 컬럼에는 실제 NaN 결측치가 없었음
- 'COM_ONE_TY'~'COM_SIX_TY'는 동행인 유형을 여러 개 기록하는 컬럼
- 동행인 수가 적으면 뒤쪽 컬럼이 비어 있는 구조이므로, 해당 결측치는 데이터 손상이 아닌 설문 구조상 발생한 결측치로 판단
- 현재 EDA에서 동행인 유형 컬럼을 사용하지 않으므로 별도의 대체나 삭제를 수행하지 않았음
- 단, 여행기간과 여행비용의 '모름'은 NaN은 아니지만 분석 목적에 따라 제외하여 사용

### 3.이상치 처리

In [228]:
# 주요 범주형 변수 값 확인
for col in [
    'TOUR_CTPRVN_NM_x',
    'TOUR_SIGNGU_NM_x',
    'TOUR_PD_VALUE_x',
    'TOUR_PURPS_NM'
]:
    print(f'\n[{col}]')
    print(df[col].value_counts())

[TOUR_CTPRVN_NM_x]
TOUR_CTPRVN_NM_x
강원도     2931
경기도     1227
경상북도    1203
전라남도    1168
부산시     1153
제주도     1041
경상남도     950
서울시      907
충청남도     885
전라북도     757
충청북도     553
인천시      502
대전시      352
대구시      332
울산시      223
광주시      158
Name: count, dtype: int64

[TOUR_SIGNGU_NM_x]
TOUR_SIGNGU_NM_x
모름                          3627
강릉시                          532
속초시                          527
경주시                          346
여수시                          269
                            ...
강진군/나주시/보성군/여수시                1
용인시/파주시                        1
제천시/청주시                        1
대정읍/애월읍/제주시(시내동)/한경면/한림읍       1
남해군/사천시/진주시/함안군                1
Name: count, Length: 1304, dtype: int64

[TOUR_PD_VALUE_x]
TOUR_PD_VALUE_x
1박 2일       7196
2박 3일       4121
3박 4일       1553
4박 5일        639
6박 7일 이상     485
5박 6일        204
모름           144
Name: count, dtype: int64

[TOUR_PURPS_NM]
TOUR_PURPS_NM
자연 풍경 감상 (산/ 바다 등)         3090
휴식                         2797
식도락 (지역 특색/제철 음식)          2340
친지/친구/친척 만나기               2325
놀이/테마공원-온천 등 즐기기            837
역사-유적 감상 (유적지/ 박물관 등)       710
취미-운동 활동 (등산/ 낚시/ 골프 등)     620
축제-행사 참여                    414
문화-예술 즐기기 (미술관/ 공연 등)       400
도시 경관 감상 (건축물/ 거리 등)        400
쇼핑                          248
기타                          161
Name: count, dtype: int64

In [229]:
# 분석에 사용할 주요 컬럼의 실제 값 확인
cols = [
    'TOUR_BEGIN_DE',          # 여행시작일자
    'TOUR_CTPRVN_NM_x',       # 여행시도명
    'TOUR_SIGNGU_NM_x',       # 여행시군구명
    'TOUR_PD_VALUE_x',        # 여행기간
    'TOUR_PURPS_NM',          # 여행목적
    'TOUR_TOT_CT_VALUE'       # 여행총비용
]

for col in cols:
    print(f'\n[{col}]')
    print(df[col].value_counts(dropna=False).head(10))

[TOUR_BEGIN_DE]
TOUR_BEGIN_DE
20250301    269
20250815    267
20250503    266
20250606    261
20251003    155
20250801    144
20250502    137
20250405    132
20250814    129
20250412    126
Name: count, dtype: int64

[TOUR_CTPRVN_NM_x]
TOUR_CTPRVN_NM_x
강원도     2931
경기도     1227
경상북도    1203
전라남도    1168
부산시     1153
제주도     1041
경상남도     950
서울시      907
충청남도     885
전라북도     757
Name: count, dtype: int64

[TOUR_SIGNGU_NM_x]
TOUR_SIGNGU_NM_x
모름     3627
강릉시     532
속초시     527
경주시     346
여수시     269
태안군     162
거제시     162
전주시     160
포항시     155
고성군     151
Name: count, dtype: int64

[TOUR_PD_VALUE_x]
TOUR_PD_VALUE_x
1박 2일       7196
2박 3일       4121
3박 4일       1553
4박 5일        639
6박 7일 이상     485
5박 6일        204
모름           144
Name: count, dtype: int64

[TOUR_PURPS_NM]
TOUR_PURPS_NM
자연 풍경 감상 (산/ 바다 등)         3090
휴식                         2797
식도락 (지역 특색/제철 음식)          2340
친지/친구/친척 만나기               2325
놀이/테마공원-온천 등 즐기기            837
역사-유적 감상 (유적지/ 박물관 등)       710
취미-운동 활동 (등산/ 낚시/ 골프 등)     620
축제-행사 참여                    414
문화-예술 즐기기 (미술관/ 공연 등)       400
도시 경관 감상 (건축물/ 거리 등)        400
Name: count, dtype: int64

[TOUR_TOT_CT_VALUE]
TOUR_TOT_CT_VALUE
10~20만원 미만    4017
20~30만원 미만    2941
모름            2639
40만원 이상       1870
30~40만원 미만    1733
10만원 미만       1142
Name: count, dtype: int64

이상치 확인 결과

- 지역, 여행기간, 여행목적, 여행 총비용의 고유값과 빈도를 확인
- 여행기간은 '1박 2일'부터 '6박 7일 이상', 여행 총비용은 '10만원 미만'부터 '40만원 이상'의 범주형 구간으로 구성되어 있음
- 데이터 범위를 벗어난 비정상적인 범주값은 발견되지 않아서 별도의 이상치 삭제는 수행하지 않음
- '모름'은 이상치가 아니라 미응답 값이므로 관련 분석에서만 제외

### 4.손상된 레코드 처리

In [230]:
df['TOUR_BEGIN_DE'].head()

0    20250810
1    20251028
2    20250908
3    20251008
4    20251114
Name: TOUR_BEGIN_DE, dtype: int64

In [231]:
df['TOUR_BEGIN_DE'].dtype

dtype('int64')

In [232]:
# 여행 시작일 날짜형으로 변환
df['TOUR_BEGIN_DE'] = pd.to_datetime(
    df['TOUR_BEGIN_DE'].astype(str),
    format='%Y%m%d',
    errors='coerce'
)

# 확인
df['TOUR_BEGIN_DE'].head()

0   2025-08-10
1   2025-10-28
2   2025-09-08
3   2025-10-08
4   2025-11-14
Name: TOUR_BEGIN_DE, dtype: datetime64[ns]

In [233]:
df['TOUR_BEGIN_DE'].min(), df['TOUR_BEGIN_DE'].max()

(Timestamp('2025-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [234]:
df['TOUR_BEGIN_DE'].isnull().sum()

np.int64(0)

In [235]:
# 1. 중복 데이터 확인
print('중복 행:', df.duplicated().sum())

# 2. 지역명 확인
print(df['TOUR_CTPRVN_NM_x'].value_counts(dropna=False))

# 3. 여행 시작일 범위 확인
print('최소 날짜:', df['TOUR_BEGIN_DE'].min())
print('최대 날짜:', df['TOUR_BEGIN_DE'].max())

중복 행: 0
TOUR_CTPRVN_NM_x
강원도     2931
경기도     1227
경상북도    1203
전라남도    1168
부산시     1153
제주도     1041
경상남도     950
서울시      907
충청남도     885
전라북도     757
충청북도     553
인천시      502
대전시      352
대구시      332
울산시      223
광주시      158
Name: count, dtype: int64
최소 날짜: 2025-01-01 00:00:00
최대 날짜: 2025-12-31 00:00:00

손상 레코드 확인 결과

- 여행 시작일을 날짜형으로 변환했으며, 변환에 실패한 값은 0건
- 여행 시작일은 2025년 1월 1일부터 2025년 12월 31일까지로 정상 범위에 포함
- 전체 행을 기준으로 확인한 결과 중복 레코드는 0건
- 지역명에서도 분석 범위를 벗어난 값이 발견되지 않음
- 따라서 삭제하거나 수정할 손상 레코드는 없는 것으로 판단

### 5.파생변수 생성

#### 5-1.여행 월 파생변수 생성

In [236]:
# 여행 시작일에서 월 추출
df['TOUR_MONTH'] = df['TOUR_BEGIN_DE'].dt.month

# 확인
df['TOUR_MONTH'].value_counts().sort_index()

TOUR_MONTH
1      647
2     1152
3     1283
4     1305
5     1550
6     1386
7     1347
8     1704
9     1317
10    1242
11     915
12     494
Name: count, dtype: int64

#### 5-2.숙박일수 파생변수 생성

In [237]:
# 여행기간을 숙박일수로 변환
period_map = {
    '1박 2일': 1,
    '2박 3일': 2,
    '3박 4일': 3,
    '4박 5일': 4,
    '5박 6일': 5,
    '6박 7일 이상': 6
}

df['숙박일수'] = df['TOUR_PD_VALUE_x'].map(period_map)

# 확인
df[['TOUR_PD_VALUE_x', '숙박일수']].head(10)

  TOUR_PD_VALUE_x  숙박일수
0        6박 7일 이상   6.0
1           1박 2일   1.0
2        6박 7일 이상   6.0
3           2박 3일   2.0
4           2박 3일   2.0
5           2박 3일   2.0
6           3박 4일   3.0
7           1박 2일   1.0
8           2박 3일   2.0
9           1박 2일   1.0

In [238]:
# 숙박일수로 변환되지 않은 원본 값 확인
df.loc[
    df['숙박일수'].isnull(),
    ['TOUR_PD_VALUE_x', '숙박일수']
].value_counts(dropna=False)

TOUR_PD_VALUE_x  숙박일수
모름               NaN     144
Name: count, dtype: int64

#### 5-3.고지출 여부 파생변수 생성

In [239]:
# 고지출 여부 파생변수 생성
# 우선 모든 행을 결측값으로 설정
df['고지출여부'] = pd.Series(
    pd.NA,
    index=df.index,
    dtype='boolean'
)

# 총비용이 '모름'이 아닌 행
known_expense = df['TOUR_TOT_CT_VALUE'] != '모름'

# 총비용이 30만원 이상이면 True, 미만이면 False
df.loc[known_expense, '고지출여부'] = (
    df.loc[known_expense, 'TOUR_TOT_CT_VALUE']
    .isin(['30~40만원 미만', '40만원 이상'])
)

In [240]:
# 여행 총비용이 확인된 데이터만 고지출 분석에 사용
expense_df = df[df['고지출여부'].notna()].copy()

In [241]:
df[
    ['TOUR_TOT_CT_VALUE', '고지출여부']
].value_counts(dropna=False)

TOUR_TOT_CT_VALUE  고지출여부
10~20만원 미만         False    4017
20~30만원 미만         False    2941
모름                 <NA>     2639
40만원 이상            True     1870
30~40만원 미만         True     1733
10만원 미만            False    1142
Name: count, dtype: int64

#### 5-4.세부 지출 점수 파생변수 생성

In [242]:
# 점수로 변환할 세부 지출 항목
expense_cols = [
    'TOUR_LDGMNT_CT_VALUE',    # 숙박비
    'TOUR_FOOD_CT_VALUE',      # 음식비
    'TOUR_TRNSPORT_CT_VALUE',  # 교통비
    'TOUR_SHOPNG_CT_VALUE',    # 쇼핑비
    'TOUR_ACTVTY_CT_VALUE',    # 액티비티비
    'TOUR_ETC_CT_VALUE'        # 기타비용
]

In [243]:
# 세부 지출 구간을 비교하기 위한 점수
expense_score = {
    '1만원 미만': 1,
    '1~3만원 미만': 2,
    '3~5만원 미만': 3,
    '5~7만원 미만': 4,
    '7~10만원 미만': 5,
    '10만원 이상': 6
}

In [244]:
# 세부 지출 항목을 1~6점으로 변환
for col in expense_cols:
    df[col + '_SCORE'] = df[col].map(expense_score)

In [245]:
# 숙박비를 예시로 원본 값과 점수 비교
df[[
    'TOUR_LDGMNT_CT_VALUE',
    'TOUR_LDGMNT_CT_VALUE_SCORE'
]].head(10)

  TOUR_LDGMNT_CT_VALUE  TOUR_LDGMNT_CT_VALUE_SCORE
0                   모름                         NaN
1            7~10만원 미만                         5.0
2              10만원 이상                         6.0
3             5~7만원 미만                         4.0
4                   모름                         NaN
5                   모름                         NaN
6               1만원 미만                         1.0
7             5~7만원 미만                         4.0
8              10만원 이상                         6.0
9                   모름                         NaN

In [305]:
df.to_csv('../../data/cleaned/seunghee_travel_timing_expenditure_2025_cleaned.csv', index=False, encoding="utf-8-sig")